### ISSUE TITLE
Trouble with migration

### ISSUE THREAD

**Issue by radiodrag** [SpatiumPrinceps/LandLord#10]
On the Landlord-V2 (build 45), i've tried the "/ll migrate v2 sqlite" command and nothing happens, not even on the console.
I still have the old database (landlord.db) so i tested "/ll migrate v1" however, the console throw this error:
`[16:06:16] [Server thread/INFO]: NekoSenpaiii issued server command: /ll migrate v1 sqlite
[16:06:16] [Server thread/INFO]: [Landlord] Starting to migrate from v1 Ebean Database...
[16:06:16] [Server thread/WARN]: [Landlord] Error while getting result set for query: SELECT * FROM ?
Error:[SQLITE_ERROR] SQL error or missing database (near "?": syntax error)
[16:06:16] [Server thread/INFO]: [Landlord] Finished fetching data from old database. Size: 0 lands
[16:06:16] [Server thread/INFO]: [Landlord] The next step will take around 0 minutes
[16:06:16] [Server thread/INFO]: [Landlord] Finished migrating database. Migrated 0 lands!
[16:06:16] [Server thread/WARN]: [Landlord] Task #30 for Landlord v1.0 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_131]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_131]
	at biz.princeps.landlord.commands.Landlordbase$4.run(Landlordbase.java:236) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-b78586d-753a8e7]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-b78586d-753a8e7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-b78586d-753a8e7]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-b78586d-753a8e7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-b78586d-753a8e7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-b78586d-753a8e7]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]`

EDIT: I wonder, could it be because my worldguard isn't on MySQL?

**Comment by SpatiumPrinceps** [comment]
Haha I'm so stupid. I entered the wrong name for the v2 sqlite db, so it tried to open a file which did not exist at all. In addition to that I closed a curly break to early. I tested it with a 63k database, it seems to convert flawless now.
Your cpu speed is maybe different than mine, which could cause (in theoretical theory) problems. Need to find a solution for that problem xD

**Comment by radiodrag** [comment]
i confirm that this is fixed
