### ISSUE TITLE
Error in ll manage

### ISSUE THREAD

**Issue by radiodrag** [SpatiumPrinceps/LandLord#13]
`[15:15:43] [Server thread/INFO]: NekoSenpaiii issued server command: /ll manage
[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] Exception in command: ll manage 
[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] java.lang.reflect.InvocationTargetException

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at java.lang.reflect.Method.invoke(Unknown Source)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at co.aikar.commands.RegisteredCommand.invoke(RegisteredCommand.java:140)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at co.aikar.commands.BaseCommand.executeCommand(BaseCommand.java:405)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at co.aikar.commands.BaseCommand.execute(BaseCommand.java:321)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at co.aikar.commands.BukkitRootCommand.execute(BukkitRootCommand.java:78)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at co.aikar.commands.BukkitRootCommand.execute(BukkitRootCommand.java:64)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at java.util.concurrent.FutureTask.run(Unknown Source)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] 	at java.lang.Thread.run(Unknown Source)

[15:15:43] [Server thread/ERROR]: [Landlord] [ACF] Caused by: java.lang.NullPointerException

`

**Comment by SpatiumPrinceps** [comment]
Are you sure you arent missing any lines? the most important line is missing....

**Comment by radiodrag** [comment]
This is exactly what i have in the log:
`[15:52:10] [Server thread/INFO]: NekoSenpaiii[/127.0.0.1:59234] logged in with entity id 777 at ([world]2007.516808602336, 67.1176614608523, 3221.486783510123)
[15:52:13] [Server thread/INFO]: NekoSenpaiii issued server command: /ll manage
[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] Exception in command: ll manage 
[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] java.lang.reflect.InvocationTargetException

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at java.lang.reflect.Method.invoke(Unknown Source)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at co.aikar.commands.RegisteredCommand.invoke(RegisteredCommand.java:140)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at co.aikar.commands.BaseCommand.executeCommand(BaseCommand.java:405)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at co.aikar.commands.BaseCommand.execute(BaseCommand.java:321)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at co.aikar.commands.BukkitRootCommand.execute(BukkitRootCommand.java:78)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at co.aikar.commands.BukkitRootCommand.execute(BukkitRootCommand.java:64)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at java.util.concurrent.FutureTask.run(Unknown Source)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] 	at java.lang.Thread.run(Unknown Source)

[15:52:13] [Server thread/ERROR]: [Landlord] [ACF] Caused by: java.lang.NullPointerException

`

**Comment by SpatiumPrinceps** [comment]
Are you sure you are having the latest config version and en version? 
Take a look at the forum https://www.spigotmc.org/threads/beta-landlord-2.259023/#post-2562701

**Comment by radiodrag** [comment]
Oh, the config was ok, but i deleted the en lang file and now it works, thanks ^^

**Comment by SpatiumPrinceps** [comment]
If an error like this happens again, and the last line is something with nullpointer, just repest the step :)
