### ISSUE TITLE
Worldguard issue

### ISSUE THREAD

**Issue by SpatiumPrinceps** [SpatiumPrinceps/LandLord#4]
`[16:56:35] [Server thread/INFO]: AzoteBottle issued server command: /land claim
[16:56:35] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'land' in plugin Landlord v1.6
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644) ~[spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
    at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
    at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
    at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
    at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
    at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
    at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
    at com.sk89q.worldguard.bukkit.WorldConfiguration.getBoolean(WorldConfiguration.java:220) ~[?:?]
    at com.sk89q.worldguard.bukkit.WorldConfiguration.loadConfiguration(WorldConfiguration.java:345) ~[?:?]
    at com.sk89q.worldguard.bukkit.WorldConfiguration.<init>(WorldConfiguration.java:212) ~[?:?]
    at com.sk89q.worldguard.bukkit.ConfigurationManager.get(ConfigurationManager.java:230) ~[?:?]
    at com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(WorldGuardPlugin.java:1016) ~[?:?]
    at com.jcdesimp.landlord.pluginHooks.WorldguardHandler.canClaim(WorldguardHandler.java:42) ~[?:?]
    at com.jcdesimp.landlord.commands.Claim.execute(Claim.java:80) ~[?:?]
    at com.jcdesimp.landlord.LandlordCommandExecutor.onCommand(LandlordCommandExecutor.java:65) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
    ... 15 more`

Probably something with worldguard region manager returning null

**Comment by SpatiumPrinceps** [comment]
Not relevant for landlord 2
