### ISSUE TITLE
Friendall need a reload to take effect

### ISSUE THREAD

**Issue by radiodrag** [SpatiumPrinceps/LandLord#7]
The command works and i can see the changes in the database but people still don't have access to the land, works only after a server restart or a reload of the plugin

**Comment by SpatiumPrinceps** [comment]
Its fixed for me :)

**Comment by radiodrag** [comment]
I confirm, it does works, there's a huge lag when doing the Friendall though, but it works

**Comment by SpatiumPrinceps** [comment]
Yea I can see where this comes from. I'm not having any lag with a local sqlite db and 10 lands, but I think I fixed it :)

**Comment by radiodrag** [comment]
Now it don't work :\ i even restarted the whole server to be sure, but with no luck :(

**Comment by SpatiumPrinceps** [comment]
You are on build 36? 
All the database stuff is handled async, so there should not be any lag at all

**Comment by radiodrag** [comment]
yup, on build 36

**Comment by SpatiumPrinceps** [comment]
When I tested friendall it did work... 
However, my database is fairly small. 
Are there any stacktraces?

**Comment by radiodrag** [comment]
`[18:56:48] [Server thread/INFO]: NekoSenpaiii issued server command: /ll friendall XavierGames
[18:56:48] [Craft Scheduler Thread - 12/WARN]: [Landlord] Plugin Landlord v1.6 generated an exception while executing task 5074
java.lang.IllegalStateException: Asynchronous entity track!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.EntityTracker.addEntity(EntityTracker.java:108) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.EntityTracker.track(EntityTracker.java:82) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.WorldManager.a(WorldManager.java:21) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.World.b(World.java:1093) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.WorldServer.b(WorldServer.java:1160) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:1125) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.Chunk.addEntities(Chunk.java:753) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:131) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at com.jcdesimp.landlord.persistantData.OwnedLand.getChunk(OwnedLand.java:72) ~[?:?]
	at com.jcdesimp.landlord.commands.FriendAll$1.run(FriendAll.java:68) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]`

**Comment by radiodrag** [comment]
It's fixed, i confirm 😄
