### ISSUE TITLE
Plugin Conflict

### ISSUE THREAD

**Issue by KohGeek** [SpatiumPrinceps/LandLord#75]
Landlords 2 b162 seems to have issue loading when I have TrollCommands installed.

I'm running on Windows 10, and unknown Linux Host, running on Java 8 1.8.171, running on Spigot-1.12.2.

[TrollCommands++ 6.28.53](https://www.spigotmc.org/resources/trollcommands-troll-your-frenemies.24237/)

Links to related issues on respective plugins:
[ViaVersion Issues](https://github.com/MylesIsCool/ViaVersion/issues/825)
[TrollCommands++ Issues](https://github.com/egg82/TrollCommandsPlusPlus/issues/6)

Crash log of testing:
```
[00:03:58 ERROR]: Error occurred while enabling Landlord v1.162 (Is it up to date?)
java.lang.NoSuchMethodError: org.reflections.ReflectionUtils.withAnnotation(Ljava/lang/Class;)Lshaded/com/google/common/base/Predicate;
        at biz.princeps.lib.storage.DatabaseAPI.saveObject(DatabaseAPI.java:159) ~[?:?]
        at biz.princeps.landlord.Landlord.handleDatabase(Landlord.java:204) ~[?:?]
        at biz.princeps.landlord.Landlord.onEnable(Landlord.java:111) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
```

**Comment by SpatiumPrinceps** [comment]
Fixed in b166. Was a relocation issue. 
Thank you @MylesIsCool :)
