### ISSUE TITLE
problem with LandLord in 1.12

### ISSUE THREAD

**Issue by Ibiky** [SpatiumPrinceps/LandLord#8]
Hello I have a problem with LandLord in 1.12 I have a mesage / ll [command] or / land [command] that appears all the time and no function works on the server.

Thank you for your future reply, cordially Ibiki

**Comment by SpatiumPrinceps** [comment]
Hello,
which build are you using? 
Are you running on the latest spigot?
Are you running on java 8? 
Do you have a log file for me?
Greetings, Spatium

**Comment by Ibiky** [comment]
Hello,
I use LandLord version 1.4 here: https://dev.bukkit.org/projects/landlord, so I use Bukkit 1.12, and a version of Java 8.

`[22:22:41] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Landlord v1.4.1

org.bukkit.event.EventException: null

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit-1.12.jar:git-Bukkit-bb4ae3b]

	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.12.jar:git-Bukkit-bb4ae3b]

	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:498) [craftbukkit-1.12.jar:git-Bukkit-bb4ae3b]

	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:483) [craftbukkit-1.12.jar:git-Bukkit-bb4ae3b]

	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:634) [craftbukkit-1.12.jar:git-Bukkit-bb4ae3b]

	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [craftbukkit-1.12.jar:git-Bukkit-bb4ae3b]

	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [craftbukkit-1.12.jar:git-Bukkit-bb4ae3b]

	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.12.jar:git-Bukkit-bb4ae3b]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]

	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit-1.12.jar:git-Bukkit-bb4ae3b]

	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:695) [craftbukkit-1.12.jar:git-Bukkit-bb4ae3b]

	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:366) [craftbukkit-1.12.jar:git-Bukkit-bb4ae3b]

	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:650) [craftbukkit-1.12.jar:git-Bukkit-bb4ae3b]

	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit-1.12.jar:git-Bukkit-bb4ae3b]

	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

Caused by: java.lang.NullPointerException

	at com.jcdesimp.landlord.Landlord.getDatabase(Landlord.java:294) ~[?:?]

	at com.jcdesimp.landlord.persistantData.OwnedLand.getLandFromDatabase(OwnedLand.java:101) ~[?:?]

	at com.jcdesimp.landlord.persistantData.OwnedLand.getApplicableLand(OwnedLand.java:75) ~[?:?]

	at com.jcdesimp.landlord.LandAlerter.landAlertPlayer(LandAlerter.java:42) ~[?:?]

	at com.jcdesimp.landlord.LandAlerter.alertPlayerMove(LandAlerter.java:113) ~[?:?]

	at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit-1.12.jar:git-Bukkit-bb4ae3b]

	... 15 more`

Thank you again for your reply.

**Comment by SpatiumPrinceps** [comment]
You should use the updated version from my build server
http://ci.princeps.biz:7777/job/LandLord/

**Comment by Ibiky** [comment]
Thank you very much, it works correctly you are a genius, I do not know how to thank you.

**Comment by SpatiumPrinceps** [comment]
Your welcome :)
If have an existing database use /ll migrate.
Make sure to enter valid mysql credentials if you want to use mysql. Otherwise it will use a simple sqlite db. 
If anything else comes up, feel free to open a new issue
